#!/bin/bash

# Modify the backlight brightness by the given percentage.
# Usage:
#   brightness [PERCENTAGE]

get_brightness() {
  xrandr --verbose | grep -w "$1" -a10 | grep -m1 'Brightness:' | cut -f2- -d: | sed 's/\s//'
}

set_brightness() {
  xrandr --output "$1" --brightness "$2"
}

list_displays() {
  echo $(xrandr | grep -w connected | cut -f1 -d' ')
}

if [[ -n $1 ]]; then
  for display in $(list_displays); do
    val=$(get_brightness)
    new_val=$(python3 -c "print(max(min($val + ($1 / 100), 1), 0))")
    set_brightness $display $new_val
  done
  exit 0
fi

exit 1
